#!/bin/sh
# install-target-hooks.sh — Install pre-commit hook in a target repo.
#
# Usage:
#   .opencode/scripts/install-target-hooks.sh [--repo <path>]
#
# What it does:
#   1. Resolves the target repo (via --repo, $TARGET_REPO_ROOT, or CWD git root)
#   2. Detects the stack (maven/node/terraform) via filesystem markers
#   3. Generates scripts/pre-commit.sh inside the target repo (stack-appropriate)
#   4. Installs a symlink .git/hooks/pre-commit → ../../scripts/pre-commit.sh
#
# The generated pre-commit.sh delegates to workspace-level harness scripts
# (lint-structure.sh, build-verify.sh, test-related.sh) which already handle
# stack detection. The target repo's script sets up the environment (staged files,
# TARGET_REPO_ROOT, WORKSPACE_ROOT) and delegates.
#
# Idempotent: safe to re-run. Overwrites existing scripts/pre-commit.sh.
set -e

__SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"

# --- Parse args ---
while [ $# -gt 0 ]; do
  case "$1" in
    --repo) shift; REPO_ARG="$1"; shift ;;
    *)      REPO_ARG="$1"; shift ;;
  esac
done

# --- Resolve target repo (lightweight, no guard against workspace) ---
WORKSPACE_ROOT="$(CDPATH= cd -- "$__SCRIPT_DIR/../.." && pwd)"
export WORKSPACE_ROOT

if [ -n "${REPO_ARG:-}" ]; then
  TARGET_REPO_ROOT="$(CDPATH= cd -- "$REPO_ARG" 2>/dev/null && pwd || printf '%s' "$REPO_ARG")"
elif [ -n "${TARGET_REPO_ROOT:-}" ]; then
  true  # already set
else
  TARGET_REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
fi

if [ ! -d "$TARGET_REPO_ROOT/.git" ]; then
  echo "[juninho:install-hooks] Not a git repo: $TARGET_REPO_ROOT" >&2
  exit 1
fi

cd "$TARGET_REPO_ROOT"

# --- Detect stack ---
. "$__SCRIPT_DIR/_detect-stack.sh"
STACK="$(detect_stack)"
echo "[juninho:install-hooks] Target: $TARGET_REPO_ROOT"
echo "[juninho:install-hooks] Detected stack: $STACK"

# --- Ensure scripts/ directory exists ---
mkdir -p "$TARGET_REPO_ROOT/scripts"

# --- Generate scripts/pre-commit.sh ---
PRECOMMIT="$TARGET_REPO_ROOT/scripts/pre-commit.sh"

cat > "$PRECOMMIT" << 'GENERATED_EOF'
#!/bin/sh
# Generated by juninho harness — install-target-hooks.sh
# This script runs fast local checks on staged files before each commit.
# It delegates to workspace-level harness scripts that are stack-aware.
set -e

ROOT_DIR="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$ROOT_DIR"

# --- Locate workspace (harness) root ---
# Convention: workspace is always at ~/repos (or wherever .opencode/ lives).
# The JUNINHO_WORKSPACE env var overrides if set.
if [ -n "${JUNINHO_WORKSPACE:-}" ]; then
  WORKSPACE_ROOT="$JUNINHO_WORKSPACE"
elif [ -d "$ROOT_DIR/../../.opencode/scripts" ]; then
  WORKSPACE_ROOT="$(CDPATH= cd -- "$ROOT_DIR/../.." && pwd)"
elif [ -d "$ROOT_DIR/../../../.opencode/scripts" ]; then
  WORKSPACE_ROOT="$(CDPATH= cd -- "$ROOT_DIR/../../.." && pwd)"
else
  echo "[juninho:pre-commit] Cannot locate workspace root (.opencode/scripts not found)." >&2
  echo "[juninho:pre-commit] Set JUNINHO_WORKSPACE=/path/to/workspace or re-run install-target-hooks.sh" >&2
  exit 1
fi

export TARGET_REPO_ROOT="$ROOT_DIR"
export WORKSPACE_ROOT
export ALLOW_WORKSPACE_GIT=0

# --- Collect staged files ---
JUNINHO_STAGED_FILES="$(git diff --cached --name-only --diff-filter=ACMR)"
export JUNINHO_STAGED_FILES

if [ -z "$JUNINHO_STAGED_FILES" ]; then
  echo "[juninho:pre-commit] No staged files. Skipping."
  exit 0
fi

# --- Source config reader for toggles ---
. "$WORKSPACE_ROOT/.opencode/scripts/_read-config.sh"

# --- Run checks (respecting config toggles) ---
if config_get_workflow_bool implement.skipLintOnPrecommit false; then
  echo "[juninho:pre-commit] Skipping lint (workflow.implement.skipLintOnPrecommit=true)"
else
  echo "[juninho:pre-commit] Running structure lint..."
  "$WORKSPACE_ROOT/.opencode/scripts/lint-structure.sh"
fi

echo "[juninho:pre-commit] Running build verification..."
"$WORKSPACE_ROOT/.opencode/scripts/build-verify.sh"

if config_get_workflow_bool implement.skipTestOnPrecommit false; then
  echo "[juninho:pre-commit] Skipping tests (workflow.implement.skipTestOnPrecommit=true)"
else
  echo "[juninho:pre-commit] Running related tests..."
  "$WORKSPACE_ROOT/.opencode/scripts/test-related.sh"
fi

echo "[juninho:pre-commit] All checks passed"
GENERATED_EOF

chmod +x "$PRECOMMIT"
echo "[juninho:install-hooks] Generated: $PRECOMMIT"

# --- Install symlink ---
HOOKS_DIR="$TARGET_REPO_ROOT/.git/hooks"
HOOK_TARGET="$HOOKS_DIR/pre-commit"

if [ -L "$HOOK_TARGET" ] || [ -f "$HOOK_TARGET" ]; then
  rm -f "$HOOK_TARGET"
fi

ln -sf ../../scripts/pre-commit.sh "$HOOK_TARGET"
chmod +x "$HOOK_TARGET"
echo "[juninho:install-hooks] Installed symlink: .git/hooks/pre-commit → ../../scripts/pre-commit.sh"
echo "[juninho:install-hooks] Done"
