#!/bin/sh
# install-target-hooks.sh — Install pre-commit hook in a target repo.
#
# Usage:
#   .opencode/scripts/install-target-hooks.sh [--repo <path>]
#
# What it does:
#   1. Resolves the target repo (via --repo, $TARGET_REPO_ROOT, or CWD git root)
#   2. Detects the stack (maven/node/terraform) via filesystem markers
#   3. Generates scripts/pre-commit.sh inside the target repo (stack-appropriate)
#   4. Installs a symlink .git/hooks/pre-commit → ../../scripts/pre-commit.sh
#
# The generated pre-commit.sh delegates to workspace-level harness scripts
# (lint-structure.sh, build-verify.sh, test-related.sh) which already handle
# stack detection. The target repo's script sets up the environment (staged files,
# TARGET_REPO_ROOT, WORKSPACE_ROOT) and delegates.
#
# Idempotent: safe to re-run. Overwrites existing scripts/pre-commit.sh.
set -e

__SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"

# --- Parse args ---
while [ $# -gt 0 ]; do
  case "$1" in
    --repo) shift; REPO_ARG="$1"; shift ;;
    *)      REPO_ARG="$1"; shift ;;
  esac
done

# --- Resolve target repo (lightweight, no guard against workspace) ---
WORKSPACE_ROOT="$(CDPATH= cd -- "$__SCRIPT_DIR/../.." && pwd)"
export WORKSPACE_ROOT

if [ -n "${REPO_ARG:-}" ]; then
  TARGET_REPO_ROOT="$(CDPATH= cd -- "$REPO_ARG" 2>/dev/null && pwd || printf '%s' "$REPO_ARG")"
elif [ -n "${TARGET_REPO_ROOT:-}" ]; then
  true  # already set
else
  TARGET_REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
fi

if [ ! -d "$TARGET_REPO_ROOT/.git" ]; then
  echo "[juninho:install-hooks] Not a git repo: $TARGET_REPO_ROOT" >&2
  exit 1
fi

cd "$TARGET_REPO_ROOT"

# --- Detect stack ---
. "$__SCRIPT_DIR/_detect-stack.sh"
STACK="$(detect_stack)"
echo "[juninho:install-hooks] Target: $TARGET_REPO_ROOT"
echo "[juninho:install-hooks] Detected stack: $STACK"

# --- Ensure scripts/ directory exists ---
mkdir -p "$TARGET_REPO_ROOT/scripts"

# --- Generate scripts/pre-commit.sh ---
PRECOMMIT="$TARGET_REPO_ROOT/scripts/pre-commit.sh"

cat > "$PRECOMMIT" << 'GENERATED_EOF'
#!/bin/sh
# Generated by juninho harness — install-target-hooks.sh
# This script runs fast local checks on staged files before each commit.
# It delegates to workspace-level harness scripts that are stack-aware.
set -e

ROOT_DIR="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$ROOT_DIR"

# --- Locate workspace (harness) root ---
# Convention: workspace is always at ~/repos (or wherever .opencode/ lives).
# The JUNINHO_WORKSPACE env var overrides if set.
if [ -n "${JUNINHO_WORKSPACE:-}" ]; then
  WORKSPACE_ROOT="$JUNINHO_WORKSPACE"
elif [ -d "$ROOT_DIR/../../.opencode/scripts" ]; then
  WORKSPACE_ROOT="$(CDPATH= cd -- "$ROOT_DIR/../.." && pwd)"
elif [ -d "$ROOT_DIR/../../../.opencode/scripts" ]; then
  WORKSPACE_ROOT="$(CDPATH= cd -- "$ROOT_DIR/../../.." && pwd)"
else
  echo "[juninho:pre-commit] Cannot locate workspace root (.opencode/scripts not found)." >&2
  echo "[juninho:pre-commit] Set JUNINHO_WORKSPACE=/path/to/workspace or re-run install-target-hooks.sh" >&2
  exit 1
fi

export TARGET_REPO_ROOT="$ROOT_DIR"
export WORKSPACE_ROOT
export ALLOW_WORKSPACE_GIT=0

# --- Collect staged files ---
JUNINHO_STAGED_FILES="$(git diff --cached --name-only --diff-filter=ACMR)"
export JUNINHO_STAGED_FILES

if [ -z "$JUNINHO_STAGED_FILES" ]; then
  echo "[juninho:pre-commit] No staged files. Skipping."
  exit 0
fi

# --- Source config reader for toggles + stack detection helpers ---
. "$WORKSPACE_ROOT/.opencode/scripts/_read-config.sh"
. "$WORKSPACE_ROOT/.opencode/scripts/_detect-stack.sh"

# --- Auto-apply formatting to staged files (first-pass compliance) ---
# Formatting must never fail a commit: the formatter is APPLIED to the
# fully-staged files before the checks run, and whatever it touched is
# re-staged. A failed apply never blocks (|| true) — lint-structure right
# after stays the gate.
#
# Limit: partially-staged files (staged AND with unstaged edits on top, e.g.
# git add -p) are SKIPPED by the auto-format. Formatters work on the working
# tree, so formatting them would rewrite the dev's unstaged WIP without
# consent, and re-staging would sweep unstaged hunks into the commit. Those
# files go through unformatted — the hook warns, and CI may flag them.
if config_get_workflow_bool implement.autoFixFormatOnCommit true; then
  STACK="$(detect_stack)"
  # Partition staged files: a staged file listed by `git diff --name-only`
  # has unstaged edits (partially staged); the rest are fully staged.
  __fmt_unstaged="$(git diff --name-only)"
  __fmt_full=""
  __fmt_partial=""
  while IFS= read -r __fmt_f; do
    [ -z "$__fmt_f" ] && continue
    if printf '%s\n' "$__fmt_unstaged" | grep -qxF "$__fmt_f"; then
      __fmt_partial="${__fmt_partial}${__fmt_f}
"
    else
      __fmt_full="${__fmt_full}${__fmt_f}
"
    fi
  done <<JUNINHO_STAGED_EOF
$JUNINHO_STAGED_FILES
JUNINHO_STAGED_EOF
  if [ -n "$__fmt_partial" ]; then
    __fmt_partial_count="$(printf '%s' "$__fmt_partial" | grep -c .)"
    echo "[juninho:pre-commit] WARNING: $__fmt_partial_count arquivo(s) parcialmente staged pulados pelo auto-format; o CI pode reprovar formatação:"
    printf '%s' "$__fmt_partial" | sed 's/^/  - /'
    unset __fmt_partial_count
  fi
  case "$STACK" in
    maven)
      if [ -n "$__fmt_full" ] && pom_has_plugin spotless-maven-plugin && MVN="$(maven_runner)"; then
        # spotlessFiles is a comma-separated list of regexes matched against
        # absolute paths — prefix each staged path with .*/ to anchor the tail.
        __fmt_files="$(printf '%s\n' "$__fmt_full" | sed '/^$/d; s|^|.*/|' | paste -sd, -)"
        if [ -n "$__fmt_files" ]; then
          echo "[juninho:pre-commit] Auto-applying spotless to staged files..."
          $MVN -q spotless:apply -DspotlessFiles="$__fmt_files" || true
        fi
        unset __fmt_files
      fi
      ;;
    node)
      has_prettier_config() {
        for __pc_f in .prettierrc .prettierrc.json .prettierrc.yml .prettierrc.yaml .prettierrc.js .prettierrc.cjs .prettierrc.mjs prettier.config.js prettier.config.cjs prettier.config.mjs; do
          [ -f "$__pc_f" ] && { unset __pc_f; return 0; }
        done
        unset __pc_f
        grep -q '"prettier"' package.json 2>/dev/null
      }
      if [ -n "$__fmt_full" ] && has_prettier_config && command -v npx >/dev/null 2>&1 && npx --no-install prettier --version >/dev/null 2>&1; then
        echo "[juninho:pre-commit] Auto-applying prettier to staged files..."
        __fmt_files="$(printf '%s\n' "$__fmt_full" | sed '/^$/d' | tr '\n' ' ')"
        npx --no-install prettier --write --ignore-unknown $__fmt_files || true
        unset __fmt_files
      fi
      ;;
  esac
  # Re-stage formatter output. Only fully-staged files were formatted, and
  # those had a clean working tree before the apply — so anything in that set
  # that is dirty now was touched by the formatter. Partially-staged files
  # are never re-added, so unstaged hunks stay out of the commit.
  git diff --name-only | while IFS= read -r __fmt_f; do
    printf '%s\n' "$__fmt_full" | grep -qxF "$__fmt_f" || continue
    git add -- "$__fmt_f" || true
  done
  unset __fmt_unstaged __fmt_full __fmt_partial __fmt_f
fi

# --- Run checks (respecting config toggles) ---
if config_get_workflow_bool implement.skipLintOnPrecommit false; then
  echo "[juninho:pre-commit] Skipping lint (workflow.implement.skipLintOnPrecommit=true)"
else
  echo "[juninho:pre-commit] Running structure lint..."
  "$WORKSPACE_ROOT/.opencode/scripts/lint-structure.sh"
fi

echo "[juninho:pre-commit] Running build verification..."
"$WORKSPACE_ROOT/.opencode/scripts/build-verify.sh"

if config_get_workflow_bool implement.skipTestOnPrecommit false; then
  echo "[juninho:pre-commit] Skipping tests (workflow.implement.skipTestOnPrecommit=true)"
else
  echo "[juninho:pre-commit] Running related tests..."
  "$WORKSPACE_ROOT/.opencode/scripts/test-related.sh"
fi

echo "[juninho:pre-commit] All checks passed"
GENERATED_EOF

chmod +x "$PRECOMMIT"
echo "[juninho:install-hooks] Generated: $PRECOMMIT"

# --- Install symlink ---
HOOKS_DIR="$TARGET_REPO_ROOT/.git/hooks"
HOOK_TARGET="$HOOKS_DIR/pre-commit"

if [ -L "$HOOK_TARGET" ] || [ -f "$HOOK_TARGET" ]; then
  rm -f "$HOOK_TARGET"
fi

ln -sf ../../scripts/pre-commit.sh "$HOOK_TARGET"
chmod +x "$HOOK_TARGET"
echo "[juninho:install-hooks] Installed symlink: .git/hooks/pre-commit → ../../scripts/pre-commit.sh"
echo "[juninho:install-hooks] Done"
